import type { MethodItem } from 'formula-edit-lark';
import type { AppLocale } from './i18n';

const m = (
  name: string,
  realValue: string,
  category: string,
  syntax: string,
  description: string,
  example?: string,
  defaultArgs = '(,)',
): MethodItem => ({
  name,
  value: `${name}${defaultArgs}`,
  realValue,
  category,
  syntax,
  description,
  example,
});

const ZH_METHOD_LIST: MethodItem[] = [
  m('IF', 'if', '逻辑函数', 'IF(condition, value_if_true, value_if_false)', '条件判断', 'IF(@单价>100,"贵","便宜")', '(,,)'),
  m('AND', 'and', '逻辑函数', 'AND(logical1, logical2, ...)', '所有参数为真时返回 TRUE', 'AND(TRUE, TRUE)'),
  m('OR', 'or', '逻辑函数', 'OR(logical1, logical2, ...)', '任一参数为真时返回 TRUE', 'OR(FALSE, TRUE)'),
  m('NOT', 'not', '逻辑函数', 'NOT(logical)', '对逻辑值取反', 'NOT(TRUE)'),
  m('IFS', 'ifs', '逻辑函数', 'IFS(condition1, value1, ...)', '多条件判断', 'IFS(@单价>100,"贵",@单价>50,"中","低")', '(,,)'),
  m('SWITCH', 'switch', '逻辑函数', 'SWITCH(expression, value1, result1, ...)', '按值匹配返回结果', 'SWITCH(@单选,"是",1,"否",0)'),
  m('IFERROR', 'iferror', '逻辑函数', 'IFERROR(value, value_if_error)', '出错时返回指定值', 'IFERROR(1/0, 0)'),
  m('IFNA', 'ifna', '逻辑函数', 'IFNA(value, value_if_na)', '值为 #N/A 时返回替代值', 'IFNA(VLOOKUP(1,A:B,2), 0)'),
  m('CONTAIN', 'contain', '逻辑函数', 'CONTAIN(text, substring)', '判断文本是否包含子串', 'CONTAIN("hello","ell")'),
  m('SUM', 'sum', '数学函数', 'SUM(number1, number2, ...)', '求和', 'SUM(@单价, @数量)'),
  m('AVERAGE', 'average', '数学函数', 'AVERAGE(number1, ...)', '平均值', 'AVERAGE(@单价, @数量)'),
  m('AVG', 'average', '数学函数', 'AVG(number1, ...)', '平均值（同 AVERAGE）', 'AVG(@单价)'),
  m('MIN', 'min', '数学函数', 'MIN(number1, ...)', '最小值', 'MIN(@单价, @数量)'),
  m('MAX', 'max', '数学函数', 'MAX(number1, ...)', '最大值', 'MAX(@单价, @数量)'),
  m('COUNT', 'count', '数学函数', 'COUNT(value1, ...)', '计数（数字）', 'COUNT(@单价, @数量)'),
  m('COUNTA', 'counta', '数学函数', 'COUNTA(value1, ...)', '计数（非空）', 'COUNTA(@文本, @单选)'),
  m('ROUND', 'round', '数学函数', 'ROUND(number, digits)', '四舍五入', 'ROUND(@单价*@数量, 2)', '(,2)'),
  m('ROUNDUP', 'roundup', '数学函数', 'ROUNDUP(number, digits)', '向上舍入', 'ROUNDUP(@单价, 2)', '(,2)'),
  m('ROUNDDOWN', 'rounddown', '数学函数', 'ROUNDDOWN(number, digits)', '向下舍入', 'ROUNDDOWN(@单价, 2)', '(,2)'),
  m('ABS', 'abs', '数学函数', 'ABS(number)', '绝对值', 'ABS(-5)'),
  m('MOD', 'mod', '数学函数', 'MOD(number, divisor)', '取余', 'MOD(@数量, 3)'),
  m('POWER', 'power', '数学函数', 'POWER(base, exponent)', '幂运算', 'POWER(@单价, 2)'),
  m('SQRT', 'sqrt', '数学函数', 'SQRT(number)', '平方根', 'SQRT(@数量)'),
  m('INT', 'int', '数学函数', 'INT(number)', '向下取整为整数', 'INT(@单价)'),
  m('PRODUCT', 'product', '数学函数', 'PRODUCT(number1, ...)', '乘积', 'PRODUCT(@单价, @数量)'),
  m('CONCAT', 'concat', '文本函数', 'CONCAT(text1, text2, ...)', '连接文本', 'CONCAT(@文本, "-", @单选)'),
  m('LEN', 'len', '文本函数', 'LEN(text)', '文本长度', 'LEN(@文本)'),
  m('LEFT', 'left', '文本函数', 'LEFT(text, num_chars)', '左侧截取', 'LEFT(@文本, 2)', '(,2)'),
  m('RIGHT', 'right', '文本函数', 'RIGHT(text, num_chars)', '右侧截取', 'RIGHT(@文本, 2)', '(,2)'),
  m('MID', 'mid', '文本函数', 'MID(text, start, num_chars)', '中间截取', 'MID(@文本, 2, 3)', '(,,)'),
  m('TRIM', 'trim', '文本函数', 'TRIM(text)', '去除首尾空格', 'TRIM(@文本)'),
  m('UPPER', 'upper', '文本函数', 'UPPER(text)', '转大写', 'UPPER(@文本)'),
  m('LOWER', 'lower', '文本函数', 'LOWER(text)', '转小写', 'LOWER(@文本)'),
  m('SUBSTITUTE', 'substitute', '文本函数', 'SUBSTITUTE(text, old, new)', '替换文本', 'SUBSTITUTE(@文本,"A","B")', '(,,)'),
  m('FIND', 'find', '文本函数', 'FIND(find_text, within_text)', '查找子串位置', 'FIND("A", @文本)'),
  m('SUMIF', 'sumif', '统计函数', 'SUMIF(range, criteria, sum_range)', '按条件求和', 'SUMIF(@单价,">100",@数量)', '(,,)'),
  m('COUNTIF', 'countif', '统计函数', 'COUNTIF(range, criteria)', '按条件计数', 'COUNTIF(@单选,"是")'),
  m('AVERAGEIF', 'averageif', '统计函数', 'AVERAGEIF(range, criteria, avg_range)', '按条件平均', 'AVERAGEIF(@单价,">50",@单价)'),
  m('TODAY', 'today', '日期函数', 'TODAY()', '返回今天日期', 'TODAY()', '()'),
  m('NOW', 'now', '日期函数', 'NOW()', '返回当前日期时间', 'NOW()', '()'),
  m('YEAR', 'year', '日期函数', 'YEAR(date)', '返回年份', 'YEAR(TODAY())'),
  m('MONTH', 'month', '日期函数', 'MONTH(date)', '返回月份', 'MONTH(TODAY())'),
  m('DAY', 'day', '日期函数', 'DAY(date)', '返回日', 'DAY(TODAY())'),
  m('DATEDIF', 'datedif', '日期函数', 'DATEDIF(start, end, unit)', '日期差', 'DATEDIF(TODAY(), TODAY(), "D")', '(,,)'),
];

const EN_METHOD_LIST: MethodItem[] = [
  m('IF', 'if', 'Logical', 'IF(condition, value_if_true, value_if_false)', 'Conditional', 'IF(@Unit price>100,"High","Low")', '(,,)'),
  m('AND', 'and', 'Logical', 'AND(logical1, logical2, ...)', 'TRUE if all arguments are TRUE', 'AND(TRUE, TRUE)'),
  m('OR', 'or', 'Logical', 'OR(logical1, logical2, ...)', 'TRUE if any argument is TRUE', 'OR(FALSE, TRUE)'),
  m('NOT', 'not', 'Logical', 'NOT(logical)', 'Negates a logical value', 'NOT(TRUE)'),
  m('IFS', 'ifs', 'Logical', 'IFS(condition1, value1, ...)', 'Multiple conditions', 'IFS(@Unit price>100,"High",@Unit price>50,"Mid","Low")', '(,,)'),
  m('SWITCH', 'switch', 'Logical', 'SWITCH(expression, value1, result1, ...)', 'Match value and return result', 'SWITCH(@Choice,"Yes",1,"No",0)'),
  m('IFERROR', 'iferror', 'Logical', 'IFERROR(value, value_if_error)', 'Return value if error', 'IFERROR(1/0, 0)'),
  m('IFNA', 'ifna', 'Logical', 'IFNA(value, value_if_na)', 'Return value if #N/A', 'IFNA(VLOOKUP(1,A:B,2), 0)'),
  m('CONTAIN', 'contain', 'Logical', 'CONTAIN(text, substring)', 'Whether text contains substring', 'CONTAIN("hello","ell")'),
  m('SUM', 'sum', 'Math', 'SUM(number1, number2, ...)', 'Sum', 'SUM(@Unit price, @Qty)'),
  m('AVERAGE', 'average', 'Math', 'AVERAGE(number1, ...)', 'Average', 'AVERAGE(@Unit price, @Qty)'),
  m('AVG', 'average', 'Math', 'AVG(number1, ...)', 'Average (alias of AVERAGE)', 'AVG(@Unit price)'),
  m('MIN', 'min', 'Math', 'MIN(number1, ...)', 'Minimum', 'MIN(@Unit price, @Qty)'),
  m('MAX', 'max', 'Math', 'MAX(number1, ...)', 'Maximum', 'MAX(@Unit price, @Qty)'),
  m('COUNT', 'count', 'Math', 'COUNT(value1, ...)', 'Count numbers', 'COUNT(@Unit price, @Qty)'),
  m('COUNTA', 'counta', 'Math', 'COUNTA(value1, ...)', 'Count non-empty', 'COUNTA(@Text, @Choice)'),
  m('ROUND', 'round', 'Math', 'ROUND(number, digits)', 'Round', 'ROUND(@Unit price*@Qty, 2)', '(,2)'),
  m('ROUNDUP', 'roundup', 'Math', 'ROUNDUP(number, digits)', 'Round up', 'ROUNDUP(@Unit price, 2)', '(,2)'),
  m('ROUNDDOWN', 'rounddown', 'Math', 'ROUNDDOWN(number, digits)', 'Round down', 'ROUNDDOWN(@Unit price, 2)', '(,2)'),
  m('ABS', 'abs', 'Math', 'ABS(number)', 'Absolute value', 'ABS(-5)'),
  m('MOD', 'mod', 'Math', 'MOD(number, divisor)', 'Modulo', 'MOD(@Qty, 3)'),
  m('POWER', 'power', 'Math', 'POWER(base, exponent)', 'Power', 'POWER(@Unit price, 2)'),
  m('SQRT', 'sqrt', 'Math', 'SQRT(number)', 'Square root', 'SQRT(@Qty)'),
  m('INT', 'int', 'Math', 'INT(number)', 'Round down to integer', 'INT(@Unit price)'),
  m('PRODUCT', 'product', 'Math', 'PRODUCT(number1, ...)', 'Product', 'PRODUCT(@Unit price, @Qty)'),
  m('CONCAT', 'concat', 'Text', 'CONCAT(text1, text2, ...)', 'Concatenate text', 'CONCAT(@Text, "-", @Choice)'),
  m('LEN', 'len', 'Text', 'LEN(text)', 'Text length', 'LEN(@Text)'),
  m('LEFT', 'left', 'Text', 'LEFT(text, num_chars)', 'Left substring', 'LEFT(@Text, 2)', '(,2)'),
  m('RIGHT', 'right', 'Text', 'RIGHT(text, num_chars)', 'Right substring', 'RIGHT(@Text, 2)', '(,2)'),
  m('MID', 'mid', 'Text', 'MID(text, start, num_chars)', 'Mid substring', 'MID(@Text, 2, 3)', '(,,)'),
  m('TRIM', 'trim', 'Text', 'TRIM(text)', 'Trim spaces', 'TRIM(@Text)'),
  m('UPPER', 'upper', 'Text', 'UPPER(text)', 'Uppercase', 'UPPER(@Text)'),
  m('LOWER', 'lower', 'Text', 'LOWER(text)', 'Lowercase', 'LOWER(@Text)'),
  m('SUBSTITUTE', 'substitute', 'Text', 'SUBSTITUTE(text, old, new)', 'Replace text', 'SUBSTITUTE(@Text,"A","B")', '(,,)'),
  m('FIND', 'find', 'Text', 'FIND(find_text, within_text)', 'Find substring', 'FIND("A", @Text)'),
  m('SUMIF', 'sumif', 'Statistical', 'SUMIF(range, criteria, sum_range)', 'Conditional sum', 'SUMIF(@Unit price,">100",@Qty)', '(,,)'),
  m('COUNTIF', 'countif', 'Statistical', 'COUNTIF(range, criteria)', 'Conditional count', 'COUNTIF(@Choice,"Yes")'),
  m('AVERAGEIF', 'averageif', 'Statistical', 'AVERAGEIF(range, criteria, avg_range)', 'Conditional average', 'AVERAGEIF(@Unit price,">50",@Unit price)'),
  m('TODAY', 'today', 'Date', 'TODAY()', "Today's date", 'TODAY()', '()'),
  m('NOW', 'now', 'Date', 'NOW()', 'Current date-time', 'NOW()', '()'),
  m('YEAR', 'year', 'Date', 'YEAR(date)', 'Year', 'YEAR(TODAY())'),
  m('MONTH', 'month', 'Date', 'MONTH(date)', 'Month', 'MONTH(TODAY())'),
  m('DAY', 'day', 'Date', 'DAY(date)', 'Day', 'DAY(TODAY())'),
  m('DATEDIF', 'datedif', 'Date', 'DATEDIF(start, end, unit)', 'Date difference', 'DATEDIF(TODAY(), TODAY(), "D")', '(,,)'),
];

/** 常用 Excel / 表格公式函数（随 locale 切换说明与示例） */
export function getMethodList(locale: AppLocale): MethodItem[] {
  return locale === 'en-US' ? EN_METHOD_LIST : ZH_METHOD_LIST;
}

/** @deprecated 使用 getMethodList(locale) */
export const EXCEL_METHOD_LIST = ZH_METHOD_LIST;
